"""Parser code generation.

Generates standalone Python lexer from LR(0) table and grammar.
"""
from typing import Dict, Tuple
from .yapar_parser import GrammarSpec
from .table import LRTable


def generate_parser(table: LRTable, grammar: GrammarSpec, output_path=None) -> str:
    """Generate a standalone SLR parser in Python.

    The generated parser reads tokens from the lexer and produces a parse tree.
    """
    code_parts = []

    # Header
    code_parts.append("""#!/usr/bin/env python3
\"\"\"
Auto-generated SLR parser from YAPar specification.
Do NOT edit this file by hand.
\"\"\"

import sys
from dataclasses import dataclass
from typing import Any, List, Tuple, Optional, Dict, Iterator


@dataclass
class Token:
    type: str
    lexeme: str
    line: int
    col: int


@dataclass
class ParseResult:
    success: bool
    ast: Optional[Any]
    errors: List[str]
    trace: List[Dict] = None


def create_parser_tables() -> Tuple[List[Dict], List[Dict], List[Tuple]]:
    \"\"\"Return (action_table, goto_table, productions).\"\"\"
""")

    # Generate ACTION table
    code_parts.append("    action_table = [")
    for state_idx, action_dict in enumerate(table.action):
        code_parts.append(f"        {{  # State {state_idx}")
        for symbol, (action_type, action_arg) in action_dict.items():
            code_parts.append(f'            "{symbol}": ("{action_type}", {action_arg}),')
        code_parts.append("        },")
    code_parts.append("    ]")

    # Generate GOTO table
    code_parts.append("    goto_table = [")
    for state_idx, goto_dict in enumerate(table.goto):
        code_parts.append(f"        {{  # State {state_idx}")
        for symbol, next_state in goto_dict.items():
            code_parts.append(f'            "{symbol}": {next_state},')
        code_parts.append("        },")
    code_parts.append("    ]")

    # Generate productions list
    code_parts.append("    productions = [")
    code_parts.append('        ("_START_", ("start_symbol",)),  # Augmented production (idx 0)')
    for idx, prod in enumerate(grammar.productions):
        rhs_str = ', '.join(f'"{s}"' for s in prod.rhs)
        code_parts.append(f'        ("{prod.lhs}", ({rhs_str})),  # Production {idx + 1}')
    code_parts.append("    ]")

    code_parts.append("    return action_table, goto_table, productions")

    # Main parser class
    code_parts.append("""

class SLRParser:
    \"\"\"SLR parser using precomputed action and GOTO tables.\"\"\"

    def __init__(self):
        self.action_table, self.goto_table, self.productions = create_parser_tables()
        self.trace = []

    def parse(self, tokens: Iterator[Token]) -> ParseResult:
        \"\"\"Parse a stream of tokens.\"\"\"
        token_list = list(tokens)
        token_list.append(Token("$", "", 0, 0))  # Add EOF marker

        stack = [0]  # State stack
        value_stack = []  # Value/AST stack
        token_idx = 0
        errors = []

        while True:
            state = stack[-1]
            token = token_list[token_idx]
            lookahead = token.type

            action_type, action_arg = self.action_table[state].get(lookahead, ("error", -1))

            self.trace.append({
                "state": state,
                "lookahead": lookahead,
                "action": action_type,
                "token_idx": token_idx,
                "lexeme": token.lexeme,
            })

            if action_type == "shift":
                stack.append(action_arg)
                value_stack.append(token)
                token_idx += 1

            elif action_type == "reduce":
                prod_lhs, prod_rhs = self.productions[action_arg]
                rhs_len = len(prod_rhs)

                # Pop from stacks
                if rhs_len > 0:
                    stack = stack[:-rhs_len]
                    value_stack = value_stack[:-rhs_len]

                # Push nonterminal
                state = stack[-1]
                next_state = self.goto_table[state].get(prod_lhs, -1)
                if next_state == -1:
                    errors.append(f"Parse error: undefined GOTO({state}, {prod_lhs})")
                    return ParseResult(success=False, ast=None, errors=errors, trace=self.trace)

                stack.append(next_state)
                value_stack.append((prod_lhs, None))

            elif action_type == "accept":
                return ParseResult(success=True, ast=None, errors=[], trace=self.trace)

            elif action_type == "error":
                errors.append(f"Parse error at token {lookahead} ('{token.lexeme}') "
                             f"L{token.line}:C{token.col}")
                return ParseResult(success=False, ast=None, errors=errors, trace=self.trace)

            else:
                errors.append(f"Unknown action: {action_type}")
                return ParseResult(success=False, ast=None, errors=errors, trace=self.trace)


def main():
    \"\"\"Simple test: read lines, tokenize (mock), and parse.\"\"\"
    import json

    parser = SLRParser()

    # Mock: read tokens from stdin as JSON
    try:
        for line in sys.stdin:
            line = line.strip()
            if not line:
                continue
            token_data = json.loads(line)
            token = Token(**token_data)
            result = parser.parse(iter([token]))
            if not result.success:
                print(f"Error: {result.errors}")
            else:
                print("Parse successful")
    except Exception as e:
        print(f"Exception: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
""")

    code = '\n'.join(code_parts)

    if output_path:
        import pathlib
        path = pathlib.Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(code)

    return code
