"""LR(0) parser implementation.

Provides a class `LR0Parser` that uses an SLR table to parse token streams
generated by the lexer.
"""
from dataclasses import dataclass
from typing import Any, List, Iterable, Optional, Tuple
from .yapar_parser import GrammarSpec
from .lr0 import LR0Automaton
from .table import LRTable


@dataclass
class ParseResult:
    success: bool
    ast: Optional[Any]
    errors: List[str]


class LR0Parser:
    """SLR parser using LR(0) automaton and parsing table."""

    def __init__(self, grammar: GrammarSpec):
        self.grammar = grammar
        self.automaton = LR0Automaton(grammar)
        self.table = LRTable(self.automaton, grammar)
        self.trace = []

    def parse(self, token_stream: Iterable[Tuple[str, str, int, int]]) -> ParseResult:
        """Parse tokens produced by the lexer.

        `token_stream` should yield (type, lexeme, line, col) tuples.

        Returns ParseResult with success flag, AST, and any error messages.
        """
        tokens = list(token_stream)
        stack = [0]  # State stack
        value_stack = []  # Value stack for semantic actions
        token_idx = 0
        errors = []

        while True:
            # Get lookahead token
            if token_idx < len(tokens):
                lookahead_type, lookahead_val, line, col = tokens[token_idx]
            else:
                lookahead_type = "$"
                lookahead_val = ""
                line, col = 0, 0

            # Current state
            state = stack[-1]

            # Get action
            action, action_arg = self.table.get_action(state, lookahead_type)

            self.trace.append({
                "state": state,
                "lookahead": lookahead_type,
                "action": action,
                "token_idx": token_idx
            })

            if action == "shift":
                # Push state and token
                stack.append(action_arg)
                value_stack.append((lookahead_type, lookahead_val))
                token_idx += 1

            elif action == "reduce":
                # Get production
                prod = self.grammar.productions[action_arg - 1]  # -1 because 0 is augmented
                rhs_len = len(prod.rhs)

                # Pop from stacks
                stack = stack[:-rhs_len] if rhs_len > 0 else stack
                value_stack = value_stack[:-rhs_len] if rhs_len > 0 else value_stack

                # Push new nonterminal
                state = stack[-1]
                next_state = self.table.get_goto(state, prod.lhs)
                if next_state == -1:
                    errors.append(f"Parse error: invalid GOTO({state}, {prod.lhs})")
                    return ParseResult(success=False, ast=None, errors=errors)

                stack.append(next_state)
                value_stack.append((prod.lhs, None))  # Simplified: no semantic actions yet

            elif action == "accept":
                # Success!
                if len(value_stack) > 0:
                    return ParseResult(success=True, ast=value_stack[0][1], errors=[])
                return ParseResult(success=True, ast=None, errors=[])

            elif action == "error":
                errors.append(f"Parse error at token {lookahead_type} ('{lookahead_val}') "
                             f"at line {line}, column {col}")
                return ParseResult(success=False, ast=None, errors=errors)

            else:
                errors.append(f"Unknown action: {action}")
                return ParseResult(success=False, ast=None, errors=errors)
